import 'dart:ui';

/// ISO 3166-1 alpha-2 → localized country name for the achievement cards.
///
/// Deliberately a curated subset (major film-producing countries), not the
/// full ISO registry: an unknown code falls back to the raw code, which is
/// rare enough to accept. Names follow common usage, not official long forms.
const _countryEn = <String, String>{
  'AR': 'Argentina',
  'AT': 'Austria',
  'AU': 'Australia',
  'BE': 'Belgium',
  'BR': 'Brazil',
  'CA': 'Canada',
  'CH': 'Switzerland',
  'CL': 'Chile',
  'CN': 'China',
  'CO': 'Colombia',
  'CZ': 'Czechia',
  'DE': 'Germany',
  'DK': 'Denmark',
  'EG': 'Egypt',
  'ES': 'Spain',
  'FI': 'Finland',
  'FR': 'France',
  'GB': 'United Kingdom',
  'GR': 'Greece',
  'HK': 'Hong Kong',
  'HU': 'Hungary',
  'ID': 'Indonesia',
  'IE': 'Ireland',
  'IL': 'Israel',
  'IN': 'India',
  'IR': 'Iran',
  'IS': 'Iceland',
  'IT': 'Italy',
  'JP': 'Japan',
  'KR': 'South Korea',
  'LB': 'Lebanon',
  'MA': 'Morocco',
  'MX': 'Mexico',
  'MY': 'Malaysia',
  'NG': 'Nigeria',
  'NL': 'Netherlands',
  'NO': 'Norway',
  'NZ': 'New Zealand',
  'PE': 'Peru',
  'PH': 'Philippines',
  'PL': 'Poland',
  'PT': 'Portugal',
  'RO': 'Romania',
  'RU': 'Russia',
  'SA': 'Saudi Arabia',
  'SE': 'Sweden',
  'SG': 'Singapore',
  'TH': 'Thailand',
  'TR': 'Turkey',
  'TW': 'Taiwan',
  'UA': 'Ukraine',
  'US': 'United States',
  'VN': 'Vietnam',
  'ZA': 'South Africa',
};

const _countryZhHant = <String, String>{
  'AR': '阿根廷',
  'AT': '奧地利',
  'AU': '澳洲',
  'BE': '比利時',
  'BR': '巴西',
  'CA': '加拿大',
  'CH': '瑞士',
  'CL': '智利',
  'CN': '中國',
  'CO': '哥倫比亞',
  'CZ': '捷克',
  'DE': '德國',
  'DK': '丹麥',
  'EG': '埃及',
  'ES': '西班牙',
  'FI': '芬蘭',
  'FR': '法國',
  'GB': '英國',
  'GR': '希臘',
  'HK': '香港',
  'HU': '匈牙利',
  'ID': '印尼',
  'IE': '愛爾蘭',
  'IL': '以色列',
  'IN': '印度',
  'IR': '伊朗',
  'IS': '冰島',
  'IT': '義大利',
  'JP': '日本',
  'KR': '韓國',
  'LB': '黎巴嫩',
  'MA': '摩洛哥',
  'MX': '墨西哥',
  'MY': '馬來西亞',
  'NG': '奈及利亞',
  'NL': '荷蘭',
  'NO': '挪威',
  'NZ': '紐西蘭',
  'PE': '秘魯',
  'PH': '菲律賓',
  'PL': '波蘭',
  'PT': '葡萄牙',
  'RO': '羅馬尼亞',
  'RU': '俄羅斯',
  'SA': '沙烏地阿拉伯',
  'SE': '瑞典',
  'SG': '新加坡',
  'TH': '泰國',
  'TR': '土耳其',
  'TW': '台灣',
  'UA': '烏克蘭',
  'US': '美國',
  'VN': '越南',
  'ZA': '南非',
};

/// Localized country name; falls back to the raw ISO code for codes outside
/// the curated set.
String countryName(String isoCode, Locale locale) {
  final code = isoCode.toUpperCase();
  final map = locale.languageCode == 'zh' ? _countryZhHant : _countryEn;
  return map[code] ?? code;
}
